// Code generated by protoc-gen-go. DO NOT EDIT.
// source: federation.proto

package federation

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_7217fe47f5d68a8f, []int{0}
}

func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (m *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(m, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type FederationRequest struct {
	Kind                 string        `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	SelectionSet         *SelectionSet `protobuf:"bytes,2,opt,name=selectionSet,proto3" json:"selectionSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FederationRequest) Reset()         { *m = FederationRequest{} }
func (m *FederationRequest) String() string { return proto.CompactTextString(m) }
func (*FederationRequest) ProtoMessage()    {}
func (*FederationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7217fe47f5d68a8f, []int{1}
}

func (m *FederationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FederationRequest.Unmarshal(m, b)
}
func (m *FederationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FederationRequest.Marshal(b, m, deterministic)
}
func (m *FederationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FederationRequest.Merge(m, src)
}
func (m *FederationRequest) XXX_Size() int {
	return xxx_messageInfo_FederationRequest.Size(m)
}
func (m *FederationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FederationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FederationRequest proto.InternalMessageInfo

func (m *FederationRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *FederationRequest) GetSelectionSet() *SelectionSet {
	if m != nil {
		return m.SelectionSet
	}
	return nil
}

type SelectionSet struct {
	Loc                  *Location         `protobuf:"bytes,1,opt,name=loc,proto3" json:"loc,omitempty"`
	Selections           []*Selection      `protobuf:"bytes,2,rep,name=selections,proto3" json:"selections,omitempty"`
	Fragments            []*FragmentSpread `protobuf:"bytes,3,rep,name=fragments,proto3" json:"fragments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SelectionSet) Reset()         { *m = SelectionSet{} }
func (m *SelectionSet) String() string { return proto.CompactTextString(m) }
func (*SelectionSet) ProtoMessage()    {}
func (*SelectionSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_7217fe47f5d68a8f, []int{2}
}

func (m *SelectionSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectionSet.Unmarshal(m, b)
}
func (m *SelectionSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectionSet.Marshal(b, m, deterministic)
}
func (m *SelectionSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectionSet.Merge(m, src)
}
func (m *SelectionSet) XXX_Size() int {
	return xxx_messageInfo_SelectionSet.Size(m)
}
func (m *SelectionSet) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectionSet.DiscardUnknown(m)
}

var xxx_messageInfo_SelectionSet proto.InternalMessageInfo

func (m *SelectionSet) GetLoc() *Location {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *SelectionSet) GetSelections() []*Selection {
	if m != nil {
		return m.Selections
	}
	return nil
}

func (m *SelectionSet) GetFragments() []*FragmentSpread {
	if m != nil {
		return m.Fragments
	}
	return nil
}

type Location struct {
	Line                 int32    `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Column               int32    `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_7217fe47f5d68a8f, []int{3}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *Location) GetColumn() int32 {
	if m != nil {
		return m.Column
	}
	return 0
}

type Selection struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Alias                string        `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Args                 *any.Any      `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	SelectionSet         *SelectionSet `protobuf:"bytes,4,opt,name=selectionSet,proto3" json:"selectionSet,omitempty"`
	Directives           []*Directive  `protobuf:"bytes,5,rep,name=directives,proto3" json:"directives,omitempty"`
	Loc                  *Location     `protobuf:"bytes,6,opt,name=loc,proto3" json:"loc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Selection) Reset()         { *m = Selection{} }
func (m *Selection) String() string { return proto.CompactTextString(m) }
func (*Selection) ProtoMessage()    {}
func (*Selection) Descriptor() ([]byte, []int) {
	return fileDescriptor_7217fe47f5d68a8f, []int{4}
}

func (m *Selection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Selection.Unmarshal(m, b)
}
func (m *Selection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Selection.Marshal(b, m, deterministic)
}
func (m *Selection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Selection.Merge(m, src)
}
func (m *Selection) XXX_Size() int {
	return xxx_messageInfo_Selection.Size(m)
}
func (m *Selection) XXX_DiscardUnknown() {
	xxx_messageInfo_Selection.DiscardUnknown(m)
}

var xxx_messageInfo_Selection proto.InternalMessageInfo

func (m *Selection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Selection) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Selection) GetArgs() *any.Any {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Selection) GetSelectionSet() *SelectionSet {
	if m != nil {
		return m.SelectionSet
	}
	return nil
}

func (m *Selection) GetDirectives() []*Directive {
	if m != nil {
		return m.Directives
	}
	return nil
}

func (m *Selection) GetLoc() *Location {
	if m != nil {
		return m.Loc
	}
	return nil
}

type Directive struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ArgVals              *any.Any  `protobuf:"bytes,2,opt,name=argVals,proto3" json:"argVals,omitempty"`
	Loc                  *Location `protobuf:"bytes,3,opt,name=loc,proto3" json:"loc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Directive) Reset()         { *m = Directive{} }
func (m *Directive) String() string { return proto.CompactTextString(m) }
func (*Directive) ProtoMessage()    {}
func (*Directive) Descriptor() ([]byte, []int) {
	return fileDescriptor_7217fe47f5d68a8f, []int{5}
}

func (m *Directive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Directive.Unmarshal(m, b)
}
func (m *Directive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Directive.Marshal(b, m, deterministic)
}
func (m *Directive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Directive.Merge(m, src)
}
func (m *Directive) XXX_Size() int {
	return xxx_messageInfo_Directive.Size(m)
}
func (m *Directive) XXX_DiscardUnknown() {
	xxx_messageInfo_Directive.DiscardUnknown(m)
}

var xxx_messageInfo_Directive proto.InternalMessageInfo

func (m *Directive) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Directive) GetArgVals() *any.Any {
	if m != nil {
		return m.ArgVals
	}
	return nil
}

func (m *Directive) GetLoc() *Location {
	if m != nil {
		return m.Loc
	}
	return nil
}

type FragmentSpread struct {
	Loc                  *Location           `protobuf:"bytes,1,opt,name=loc,proto3" json:"loc,omitempty"`
	Fragment             *FragmentDefinition `protobuf:"bytes,2,opt,name=fragment,proto3" json:"fragment,omitempty"`
	Directives           []*Directive        `protobuf:"bytes,3,rep,name=directives,proto3" json:"directives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *FragmentSpread) Reset()         { *m = FragmentSpread{} }
func (m *FragmentSpread) String() string { return proto.CompactTextString(m) }
func (*FragmentSpread) ProtoMessage()    {}
func (*FragmentSpread) Descriptor() ([]byte, []int) {
	return fileDescriptor_7217fe47f5d68a8f, []int{6}
}

func (m *FragmentSpread) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FragmentSpread.Unmarshal(m, b)
}
func (m *FragmentSpread) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FragmentSpread.Marshal(b, m, deterministic)
}
func (m *FragmentSpread) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FragmentSpread.Merge(m, src)
}
func (m *FragmentSpread) XXX_Size() int {
	return xxx_messageInfo_FragmentSpread.Size(m)
}
func (m *FragmentSpread) XXX_DiscardUnknown() {
	xxx_messageInfo_FragmentSpread.DiscardUnknown(m)
}

var xxx_messageInfo_FragmentSpread proto.InternalMessageInfo

func (m *FragmentSpread) GetLoc() *Location {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *FragmentSpread) GetFragment() *FragmentDefinition {
	if m != nil {
		return m.Fragment
	}
	return nil
}

func (m *FragmentSpread) GetDirectives() []*Directive {
	if m != nil {
		return m.Directives
	}
	return nil
}

type FragmentDefinition struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	On                   string        `protobuf:"bytes,2,opt,name=on,proto3" json:"on,omitempty"`
	SelectionSet         *SelectionSet `protobuf:"bytes,3,opt,name=selectionSet,proto3" json:"selectionSet,omitempty"`
	Loc                  *Location     `protobuf:"bytes,4,opt,name=loc,proto3" json:"loc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FragmentDefinition) Reset()         { *m = FragmentDefinition{} }
func (m *FragmentDefinition) String() string { return proto.CompactTextString(m) }
func (*FragmentDefinition) ProtoMessage()    {}
func (*FragmentDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_7217fe47f5d68a8f, []int{7}
}

func (m *FragmentDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FragmentDefinition.Unmarshal(m, b)
}
func (m *FragmentDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FragmentDefinition.Marshal(b, m, deterministic)
}
func (m *FragmentDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FragmentDefinition.Merge(m, src)
}
func (m *FragmentDefinition) XXX_Size() int {
	return xxx_messageInfo_FragmentDefinition.Size(m)
}
func (m *FragmentDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_FragmentDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_FragmentDefinition proto.InternalMessageInfo

func (m *FragmentDefinition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FragmentDefinition) GetOn() string {
	if m != nil {
		return m.On
	}
	return ""
}

func (m *FragmentDefinition) GetSelectionSet() *SelectionSet {
	if m != nil {
		return m.SelectionSet
	}
	return nil
}

func (m *FragmentDefinition) GetLoc() *Location {
	if m != nil {
		return m.Loc
	}
	return nil
}

type FederationResponse struct {
	Data                 *any.Any        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Errors               []*GraphQLError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FederationResponse) Reset()         { *m = FederationResponse{} }
func (m *FederationResponse) String() string { return proto.CompactTextString(m) }
func (*FederationResponse) ProtoMessage()    {}
func (*FederationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7217fe47f5d68a8f, []int{8}
}

func (m *FederationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FederationResponse.Unmarshal(m, b)
}
func (m *FederationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FederationResponse.Marshal(b, m, deterministic)
}
func (m *FederationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FederationResponse.Merge(m, src)
}
func (m *FederationResponse) XXX_Size() int {
	return xxx_messageInfo_FederationResponse.Size(m)
}
func (m *FederationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FederationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FederationResponse proto.InternalMessageInfo

func (m *FederationResponse) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *FederationResponse) GetErrors() []*GraphQLError {
	if m != nil {
		return m.Errors
	}
	return nil
}

type GraphQLError struct {
	Message              string      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Locations            []*Location `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	Path                 []string    `protobuf:"bytes,3,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GraphQLError) Reset()         { *m = GraphQLError{} }
func (m *GraphQLError) String() string { return proto.CompactTextString(m) }
func (*GraphQLError) ProtoMessage()    {}
func (*GraphQLError) Descriptor() ([]byte, []int) {
	return fileDescriptor_7217fe47f5d68a8f, []int{9}
}

func (m *GraphQLError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphQLError.Unmarshal(m, b)
}
func (m *GraphQLError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphQLError.Marshal(b, m, deterministic)
}
func (m *GraphQLError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphQLError.Merge(m, src)
}
func (m *GraphQLError) XXX_Size() int {
	return xxx_messageInfo_GraphQLError.Size(m)
}
func (m *GraphQLError) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphQLError.DiscardUnknown(m)
}

var xxx_messageInfo_GraphQLError proto.InternalMessageInfo

func (m *GraphQLError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GraphQLError) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *GraphQLError) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

func init() {
	proto.RegisterType((*Null)(nil), "graphql.Null")
	proto.RegisterType((*FederationRequest)(nil), "graphql.FederationRequest")
	proto.RegisterType((*SelectionSet)(nil), "graphql.SelectionSet")
	proto.RegisterType((*Location)(nil), "graphql.Location")
	proto.RegisterType((*Selection)(nil), "graphql.Selection")
	proto.RegisterType((*Directive)(nil), "graphql.Directive")
	proto.RegisterType((*FragmentSpread)(nil), "graphql.FragmentSpread")
	proto.RegisterType((*FragmentDefinition)(nil), "graphql.FragmentDefinition")
	proto.RegisterType((*FederationResponse)(nil), "graphql.FederationResponse")
	proto.RegisterType((*GraphQLError)(nil), "graphql.GraphQLError")
}

func init() {
	proto.RegisterFile("federation.proto", fileDescriptor_7217fe47f5d68a8f)
}

var fileDescriptor_7217fe47f5d68a8f = []byte{
	// 599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x27, 0x4d, 0xff, 0x2c, 0xaf, 0xdd, 0xc4, 0xac, 0x01, 0xa1, 0xbb, 0x54, 0xe1, 0xd2, 0x0b,
	0x29, 0x2a, 0x02, 0xc4, 0x81, 0x03, 0xa8, 0x1b, 0x42, 0x4c, 0x48, 0xb8, 0x12, 0x07, 0x6e, 0x6e,
	0xe2, 0x66, 0x11, 0x89, 0x9d, 0xd9, 0xc9, 0xc4, 0xbe, 0x09, 0x27, 0x0e, 0x7c, 0x37, 0x3e, 0x01,
	0x5f, 0x00, 0xd9, 0x89, 0xd3, 0xac, 0x2d, 0xa5, 0xda, 0xa9, 0x76, 0xde, 0xef, 0xf9, 0xfd, 0xde,
	0xef, 0xf7, 0xec, 0xc2, 0xfd, 0x25, 0x0d, 0xa9, 0x20, 0x79, 0xcc, 0x99, 0x9f, 0x09, 0x9e, 0x73,
	0xd4, 0x8b, 0x04, 0xc9, 0x2e, 0xaf, 0x92, 0xe1, 0x28, 0xe2, 0x3c, 0x4a, 0xe8, 0x44, 0x7f, 0x5e,
	0x14, 0xcb, 0x49, 0x48, 0x65, 0x20, 0xe2, 0x2c, 0xe7, 0xa2, 0x84, 0x0e, 0x1f, 0xaf, 0x23, 0x08,
	0xbb, 0x29, 0x43, 0x5e, 0x17, 0xda, 0x9f, 0x8a, 0x24, 0xf1, 0x16, 0x70, 0x7c, 0x5e, 0x57, 0xc0,
	0xf4, 0xaa, 0xa0, 0x32, 0x47, 0x08, 0xda, 0xdf, 0x62, 0x16, 0xba, 0xd6, 0xc8, 0x1a, 0x3b, 0x58,
	0xaf, 0xd1, 0x6b, 0x18, 0x48, 0x9a, 0xd0, 0x40, 0xe1, 0xe6, 0x34, 0x77, 0x5b, 0x23, 0x6b, 0xdc,
	0x9f, 0x3e, 0xf0, 0x2b, 0x36, 0xfe, 0xbc, 0x11, 0xc4, 0xb7, 0xa0, 0xde, 0x4f, 0x0b, 0x06, 0xcd,
	0x30, 0x7a, 0x02, 0x76, 0xc2, 0x03, 0x7d, 0x7c, 0x7f, 0x7a, 0x5c, 0x1f, 0x71, 0xc1, 0x83, 0x92,
	0x86, 0x8a, 0xa2, 0x29, 0x40, 0x7d, 0x8a, 0x74, 0x5b, 0x23, 0x7b, 0xdc, 0x9f, 0xa2, 0xcd, 0x72,
	0xb8, 0x81, 0x42, 0x2f, 0xc0, 0x59, 0x0a, 0x12, 0xa5, 0x94, 0xe5, 0xd2, 0xb5, 0x75, 0xca, 0xa3,
	0x3a, 0xe5, 0xbc, 0x8a, 0xcc, 0x33, 0x41, 0x49, 0x88, 0x57, 0x48, 0xef, 0x25, 0x1c, 0x98, 0xda,
	0xaa, 0xf7, 0x24, 0x66, 0x54, 0x93, 0xeb, 0x60, 0xbd, 0x46, 0x0f, 0xa1, 0x1b, 0xf0, 0xa4, 0x48,
	0x99, 0xee, 0xba, 0x83, 0xab, 0x9d, 0xf7, 0xc7, 0x02, 0xa7, 0x26, 0xa2, 0x32, 0x19, 0x49, 0xa9,
	0x51, 0x4d, 0xad, 0xd1, 0x09, 0x74, 0x48, 0x12, 0x13, 0xa9, 0x13, 0x1d, 0x5c, 0x6e, 0xd0, 0x18,
	0xda, 0x44, 0x44, 0x8a, 0xa1, 0x12, 0xe0, 0xc4, 0x2f, 0x6d, 0xf2, 0x8d, 0x4d, 0xfe, 0x5b, 0x76,
	0x83, 0x35, 0x62, 0x43, 0xf5, 0xf6, 0xde, 0xaa, 0x2b, 0xfd, 0xc2, 0x58, 0xa8, 0xfd, 0x35, 0x95,
	0x6e, 0x67, 0x4d, 0xbf, 0x99, 0x09, 0xe1, 0x06, 0xca, 0x18, 0xd3, 0xdd, 0x65, 0x8c, 0x97, 0x83,
	0x53, 0x67, 0x6f, 0x6d, 0xda, 0x87, 0x1e, 0x11, 0xd1, 0x17, 0x92, 0xc8, 0x6a, 0x4a, 0xb6, 0x77,
	0x68, 0x40, 0xa6, 0xaa, 0xbd, 0xb3, 0xea, 0x2f, 0x0b, 0x8e, 0x6e, 0x3b, 0xb8, 0xdf, 0x18, 0xbd,
	0x82, 0x03, 0x63, 0x74, 0xc5, 0xe6, 0x74, 0x63, 0x22, 0x66, 0x74, 0x19, 0xb3, 0x58, 0xe7, 0xd4,
	0xe0, 0x35, 0xfd, 0xec, 0x7d, 0xf4, 0xf3, 0x7e, 0x58, 0x80, 0x36, 0x0f, 0xdd, 0x2a, 0xd2, 0x11,
	0xb4, 0x38, 0xab, 0xc6, 0xa2, 0xc5, 0xd9, 0x86, 0xd3, 0xf6, 0xfe, 0x4e, 0x57, 0x3a, 0xb4, 0x77,
	0xea, 0x97, 0x02, 0x6a, 0x5e, 0x74, 0x99, 0x71, 0x26, 0xa9, 0x9a, 0xc4, 0x90, 0xe4, 0xa4, 0xd2,
	0xf0, 0x1f, 0x93, 0xa8, 0x10, 0xe8, 0x29, 0x74, 0xa9, 0x10, 0x5c, 0x98, 0xab, 0xb8, 0x62, 0xf6,
	0x5e, 0xfd, 0x7e, 0xbe, 0x38, 0x53, 0x51, 0x5c, 0x81, 0xbc, 0x14, 0x06, 0xcd, 0xef, 0xc8, 0x85,
	0x5e, 0x4a, 0xa5, 0x24, 0x91, 0x51, 0xc1, 0x6c, 0xd1, 0x04, 0x9c, 0xa4, 0x62, 0x6a, 0xce, 0xde,
	0xd2, 0xc3, 0x0a, 0xa3, 0xd4, 0xcc, 0x48, 0x7e, 0xa9, 0x2d, 0x71, 0xb0, 0x5e, 0x4f, 0x7f, 0x5b,
	0xcd, 0x77, 0x6c, 0x4e, 0xc5, 0x75, 0x1c, 0x50, 0x34, 0x83, 0xde, 0xd9, 0x77, 0x1a, 0x14, 0x39,
	0x45, 0xc3, 0x95, 0xe9, 0xeb, 0xcf, 0xdd, 0xf0, 0x74, 0x6b, 0xac, 0x54, 0xc8, 0xbb, 0x87, 0xde,
	0xc0, 0xe1, 0x07, 0x96, 0x0b, 0x2e, 0xb3, 0xea, 0xa2, 0x1f, 0xd6, 0x78, 0xf5, 0x84, 0xfe, 0x2f,
	0xfd, 0x23, 0x0c, 0xe6, 0xc5, 0xa2, 0x7c, 0x99, 0x55, 0xf6, 0xdd, 0x99, 0x3c, 0xb3, 0xde, 0x0d,
	0xbe, 0xc2, 0xea, 0x0f, 0x61, 0xd1, 0xd5, 0x3e, 0x3d, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x9e,
	0x69, 0x83, 0x86, 0x25, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FederationServiceClient is the client API for FederationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FederationServiceClient interface {
	Execute(ctx context.Context, in *FederationRequest, opts ...grpc.CallOption) (*FederationResponse, error)
	Introspection(ctx context.Context, in *Null, opts ...grpc.CallOption) (*FederationResponse, error)
	Subscription(ctx context.Context, in *FederationRequest, opts ...grpc.CallOption) (FederationService_SubscriptionClient, error)
}

type federationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFederationServiceClient(cc grpc.ClientConnInterface) FederationServiceClient {
	return &federationServiceClient{cc}
}

func (c *federationServiceClient) Execute(ctx context.Context, in *FederationRequest, opts ...grpc.CallOption) (*FederationResponse, error) {
	out := new(FederationResponse)
	err := c.cc.Invoke(ctx, "/graphql.FederationService/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationServiceClient) Introspection(ctx context.Context, in *Null, opts ...grpc.CallOption) (*FederationResponse, error) {
	out := new(FederationResponse)
	err := c.cc.Invoke(ctx, "/graphql.FederationService/Introspection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationServiceClient) Subscription(ctx context.Context, in *FederationRequest, opts ...grpc.CallOption) (FederationService_SubscriptionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FederationService_serviceDesc.Streams[0], "/graphql.FederationService/Subscription", opts...)
	if err != nil {
		return nil, err
	}
	x := &federationServiceSubscriptionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FederationService_SubscriptionClient interface {
	Recv() (*FederationResponse, error)
	grpc.ClientStream
}

type federationServiceSubscriptionClient struct {
	grpc.ClientStream
}

func (x *federationServiceSubscriptionClient) Recv() (*FederationResponse, error) {
	m := new(FederationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FederationServiceServer is the server API for FederationService service.
type FederationServiceServer interface {
	Execute(context.Context, *FederationRequest) (*FederationResponse, error)
	Introspection(context.Context, *Null) (*FederationResponse, error)
	Subscription(*FederationRequest, FederationService_SubscriptionServer) error
}

// UnimplementedFederationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFederationServiceServer struct {
}

func (*UnimplementedFederationServiceServer) Execute(ctx context.Context, req *FederationRequest) (*FederationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (*UnimplementedFederationServiceServer) Introspection(ctx context.Context, req *Null) (*FederationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Introspection not implemented")
}
func (*UnimplementedFederationServiceServer) Subscription(req *FederationRequest, srv FederationService_SubscriptionServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscription not implemented")
}

func RegisterFederationServiceServer(s *grpc.Server, srv FederationServiceServer) {
	s.RegisterService(&_FederationService_serviceDesc, srv)
}

func _FederationService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FederationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/graphql.FederationService/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).Execute(ctx, req.(*FederationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationService_Introspection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Null)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).Introspection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/graphql.FederationService/Introspection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).Introspection(ctx, req.(*Null))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationService_Subscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FederationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FederationServiceServer).Subscription(m, &federationServiceSubscriptionServer{stream})
}

type FederationService_SubscriptionServer interface {
	Send(*FederationResponse) error
	grpc.ServerStream
}

type federationServiceSubscriptionServer struct {
	grpc.ServerStream
}

func (x *federationServiceSubscriptionServer) Send(m *FederationResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _FederationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "graphql.FederationService",
	HandlerType: (*FederationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _FederationService_Execute_Handler,
		},
		{
			MethodName: "Introspection",
			Handler:    _FederationService_Introspection_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscription",
			Handler:       _FederationService_Subscription_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "federation.proto",
}
